import { Task, TaskStatus } from '@/types/scheduling';

export const createProductTasks = (prefix: string, deadline: Date): Task[] => [
  {
    id: `${prefix}_final_assembly`,
    name: `${prefix} - Final Assembly`,
    type: 'lineitem',
    resource: 'bench',
    duration: 3,
    status: 'unscheduled',
    isFixed: false,
    dependencies: [`${prefix}_wrap_case`, `${prefix}_wrap_base_tray`, `${prefix}_line_case`],
    priority: 3,
    deadline: deadline
  },
  {
    id: `${prefix}_wrap_case`,
    name: `${prefix} - Wrap Case`,
    type: 'component',
    resource: 'gluing_machine',
    duration: 1.17,
    status: 'unscheduled',
    isFixed: false,
    dependencies: [`${prefix}_case_wrap_cut`, `${prefix}_case_board_insert`, `${prefix}_case_liner_cut`],
  },
  {
    id: `${prefix}_line_case`,
    name: `${prefix} - Line Case`,
    type: 'component',
    resource: 'gluing_machine',
    duration: 0.67,
    status: 'unscheduled',
    isFixed: false,
    dependencies: [`${prefix}_wrap_case`],
  },
  {
    id: `${prefix}_case_wrap_print`,
    name: `${prefix} - Case Wrap Print`,
    type: 'element',
    resource: 'konica',
    duration: 0.42,
    status: 'unscheduled',
    isFixed: false,
    dependencies: [],
  },
  {
    id: `${prefix}_case_wrap_laminate`,
    name: `${prefix} - Case Wrap Laminate`,
    type: 'element',
    resource: 'dk_europa',
    duration: 0.33,
    status: 'unscheduled',
    isFixed: false,
    dependencies: [`${prefix}_case_wrap_print`],
  },
  {
    id: `${prefix}_case_wrap_cut`,
    name: `${prefix} - Case Wrap Cut`,
    type: 'element',
    resource: 'zund_m800',
    duration: 0.33,
    status: 'unscheduled',
    isFixed: false,
    dependencies: [`${prefix}_case_wrap_laminate`],
  },
  {
    id: `${prefix}_case_board_cut`,
    name: `${prefix} - Case Board Cut`,
    type: 'element',
    resource: 'zund_m800',
    duration: 0.5,
    status: 'unscheduled',
    isFixed: false,
    dependencies: [],
  },
  {
    id: `${prefix}_case_board_insert`,
    name: `${prefix} - Case Board Insert`,
    type: 'element',
    resource: 'bench',
    duration: 0.5,
    status: 'unscheduled',
    isFixed: false,
    dependencies: [`${prefix}_case_board_cut`],
  },
  {
    id: `${prefix}_case_liner_laminate`,
    name: `${prefix} - Case Liner Laminate`,
    type: 'element',
    resource: 'dk_europa',
    duration: 0.33,
    status: 'unscheduled',
    isFixed: false,
    dependencies: [],
  },
  {
    id: `${prefix}_case_liner_cut`,
    name: `${prefix} - Case Liner Cut`,
    type: 'element',
    resource: 'zund_m800',
    duration: 0.33,
    status: 'unscheduled',
    isFixed: false,
    dependencies: [`${prefix}_case_liner_laminate`],
  },
  {
    id: `${prefix}_wrap_base_tray`,
    name: `${prefix} - Wrap Base Tray`,
    type: 'component',
    resource: 'gluing_machine',
    duration: 2,
    status: 'unscheduled',
    isFixed: false,
    dependencies: [
      `${prefix}_base_tray_board_corner`,
      `${prefix}_base_tray_wrap_cut`,
      `${prefix}_base_tray_board_magnets`
    ],
  },
  {
    id: `${prefix}_base_tray_board_cut`,
    name: `${prefix} - Base Tray Board Cut`,
    type: 'element',
    resource: 'zund_m800',
    duration: 1,
    status: 'unscheduled',
    isFixed: false,
    dependencies: [],
  },
  {
    id: `${prefix}_base_tray_board_drill`,
    name: `${prefix} - Base Tray Board Drill`,
    type: 'element',
    resource: 'magnet_drill',
    duration: 0.5,
    status: 'unscheduled',
    isFixed: false,
    dependencies: [`${prefix}_base_tray_board_cut`],
  },
  {
    id: `${prefix}_base_tray_board_magnets`,
    name: `${prefix} - Base Tray Board Magnets`,
    type: 'element',
    resource: 'bench',
    duration: 1,
    status: 'unscheduled',
    isFixed: false,
    dependencies: [`${prefix}_base_tray_board_drill`],
  },
  {
    id: `${prefix}_base_tray_board_corner`,
    name: `${prefix} - Base Tray Board Corner`,
    type: 'element',
    resource: 'corner_taper',
    duration: 0.5,
    status: 'unscheduled',
    isFixed: false,
    dependencies: [`${prefix}_base_tray_board_magnets`],
  },
  {
    id: `${prefix}_base_tray_wrap_print`,
    name: `${prefix} - Base Tray Wrap Print`,
    type: 'element',
    resource: 'konica',
    duration: 0.33,
    status: 'unscheduled',
    isFixed: false,
    dependencies: [],
  },
  {
    id: `${prefix}_base_tray_wrap_laminate`,
    name: `${prefix} - Base Tray Wrap Laminate`,
    type: 'element',
    resource: 'dk_europa',
    duration: 0.25,
    status: 'unscheduled',
    isFixed: false,
    dependencies: [`${prefix}_base_tray_wrap_print`],
  },
  {
    id: `${prefix}_base_tray_wrap_cut`,
    name: `${prefix} - Base Tray Wrap Cut`,
    type: 'element',
    resource: 'zund_m800',
    duration: 0.75,
    status: 'unscheduled',
    isFixed: false,
    dependencies: [`${prefix}_base_tray_wrap_laminate`],
  }
];
