import { Task, TaskStatus } from '@/types/scheduling';
import { v4 as uuidv4 } from 'uuid';

export const createProductTasks = (prefix: string, deadline: Date): Task[] => [
  {
    id: uuidv4(),
    name: `${prefix} - Final Assembly`,
    type: 'lineitem',
    resource_id: 'bench',
    duration: 3,
    status: 'unscheduled',
    is_fixed: false,
    dependencies: [],
    priority: 3,
    deadline: deadline
  },
  {
    id: uuidv4(),
    name: `${prefix} - Wrap Case`,
    type: 'component',
    resource_id: 'gluing_machine',
    duration: 1.17,
    status: 'unscheduled',
    is_fixed: false,
    dependencies: [],
  },
  {
    id: uuidv4(),
    name: `${prefix} - Line Case`,
    type: 'component',
    resource_id: 'gluing_machine',
    duration: 0.67,
    status: 'unscheduled',
    is_fixed: false,
    dependencies: [`${prefix}_wrap_case`],
  },
  {
    id: uuidv4(),
    name: `${prefix} - Case Wrap Print`,
    type: 'element',
    resource_id: 'konica',
    duration: 0.42,
    status: 'unscheduled',
    is_fixed: false,
    dependencies: [],
  },
  {
    id: uuidv4(),
    name: `${prefix} - Case Wrap Laminate`,
    type: 'element',
    resource_id: 'dk_europa',
    duration: 0.33,
    status: 'unscheduled',
    is_fixed: false,
    dependencies: [`${prefix}_case_wrap_print`],
  },
  {
    id: uuidv4(),
    name: `${prefix} - Case Wrap Cut`,
    type: 'element',
    resource_id: 'zund_m800',
    duration: 0.33,
    status: 'unscheduled',
    is_fixed: false,
    dependencies: [`${prefix}_case_wrap_laminate`],
  },
  {
    id: uuidv4(),
    name: `${prefix} - Case Board Cut`,
    type: 'element',
    resource_id: 'zund_m800',
    duration: 0.5,
    status: 'unscheduled',
    is_fixed: false,
    dependencies: [],
  },
  {
    id: uuidv4(),
    name: `${prefix} - Case Board Insert`,
    type: 'element',
    resource_id: 'bench',
    duration: 0.5,
    status: 'unscheduled',
    is_fixed: false,
    dependencies: [`${prefix}_case_board_cut`],
  },
  {
    id: uuidv4(),
    name: `${prefix} - Case Liner Laminate`,
    type: 'element',
    resource_id: 'dk_europa',
    duration: 0.33,
    status: 'unscheduled',
    is_fixed: false,
    dependencies: [],
  },
  {
    id: uuidv4(),
    name: `${prefix} - Case Liner Cut`,
    type: 'element',
    resource_id: 'zund_m800',
    duration: 0.33,
    status: 'unscheduled',
    is_fixed: false,
    dependencies: [`${prefix}_case_liner_laminate`],
  },
  {
    id: uuidv4(),
    name: `${prefix} - Wrap Base Tray`,
    type: 'component',
    resource_id: 'gluing_machine',
    duration: 2,
    status: 'unscheduled',
    is_fixed: false,
    dependencies: [
      `${prefix}_base_tray_board_corner`,
      `${prefix}_base_tray_wrap_cut`,
      `${prefix}_base_tray_board_magnets`
    ],
  },
  {
    id: uuidv4(),
    name: `${prefix} - Base Tray Board Cut`,
    type: 'element',
    resource_id: 'zund_m800',
    duration: 1,
    status: 'unscheduled',
    is_fixed: false,
    dependencies: [],
  },
  {
    id: uuidv4(),
    name: `${prefix} - Base Tray Board Drill`,
    type: 'element',
    resource_id: 'magnet_drill',
    duration: 0.5,
    status: 'unscheduled',
    is_fixed: false,
    dependencies: [`${prefix}_base_tray_board_cut`],
  },
  {
    id: uuidv4(),
    name: `${prefix} - Base Tray Board Magnets`,
    type: 'element',
    resource_id: 'bench',
    duration: 1,
    status: 'unscheduled',
    is_fixed: false,
    dependencies: [`${prefix}_base_tray_board_drill`],
  },
  {
    id: uuidv4(),
    name: `${prefix} - Base Tray Board Corner`,
    type: 'element',
    resource_id: 'corner_taper',
    duration: 0.5,
    status: 'unscheduled',
    is_fixed: false,
    dependencies: [`${prefix}_base_tray_board_magnets`],
  },
  {
    id: uuidv4(),
    name: `${prefix} - Base Tray Wrap Print`,
    type: 'element',
    resource_id: 'konica',
    duration: 0.33,
    status: 'unscheduled',
    is_fixed: false,
    dependencies: [],
  },
  {
    id: uuidv4(),
    name: `${prefix} - Base Tray Wrap Laminate`,
    type: 'element',
    resource_id: 'dk_europa',
    duration: 0.25,
    status: 'unscheduled',
    is_fixed: false,
    dependencies: [`${prefix}_base_tray_wrap_print`],
  },
  {
    id: uuidv4(),
    name: `${prefix} - Base Tray Wrap Cut`,
    type: 'element',
    resource_id: 'zund_m800',
    duration: 0.75,
    status: 'unscheduled',
    is_fixed: false,
    dependencies: [`${prefix}_base_tray_wrap_laminate`],
  }
];
