// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrhglzjydqvivydcuytl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyaGdsemp5ZHF2aXZ5ZGN1eXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE3MjM1MjAsImV4cCI6MjA0NzI5OTUyMH0.-XOMF7JXjZj7E-8GXRMrxCw7jQZPoyXex0uj_OxnQXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);